### ISSUE TITLE
Wedding License

### ISSUE THREAD

**Issue by riordan** [thaneyriordan/plan#11]
# Background:
- Weddings in NYC require a wedding license, valid for a 60 day period
- Applications can be done online
# ToDo's
- [x] Fill out online intake form from NYC
- [ ] Go to city hall to complete wedding license
  - [ ] Bring necessary paperwork
# Useful Links & Information:
- NY State's [Information on Getting Married in New York State](http://www.health.ny.gov/publications/4210/)
- NYCGO [NYC I Do](http://www.nycgo.com/articles/nyc-i-do)

**Comment by riordan** [comment]
> Your Marriage License application has been successfully submitted to the Office of the City Clerk.
> 
> PLEASE RETAIN THIS CONFIRMATION NUMBER: 8B3QPTN2. You will need it to complete your application.
> 
> In order to complete your application, you and your prospective spouse must appear together in person at the Office of the City Clerk. Proxy marriage is not permitted in New York, so no other party may apply on behalf of either prospective spouse. Visit the Office of the City Clerk Web site online to get business hours and locations.
> 
> Here's what you'll need to bring.
> To obtain a Marriage License at the Office of the City Clerk, you must present the following items:
> 
> ```
> Your confirmation number from this page,
> Your Social Security Number, if you have one,
> Payment of $35 by credit card or money order payable to the City Clerk,
> Proof of prior marriage termination (if applicable), and
> One of the following forms of proper identification:
>     Driver License with photograph (from the United States of America or any of its territories)
>     Non-Driver Identification Card with photograph (from the United States of America or any of its territories)
>     Learner Permit with photograph (from the United States of America or any of its territories)
>     Active United States Military Identification Card
>     Passport
>     United States Certificate of Naturalization (good for 10 years after date of issue)
>     United States Alien Registration Card
>     United States Employment Authorization Card 
> ```
> 
> Additional Instructions:
> Applications submitted online expire after 21 days. If you do not complete your application before then, you will need to resubmit.
> 
> Your Marriage License will expire in 60 days, or after 180 days for those on active military duty who prove their active status at the time of their application.
> 
> After you complete your Marriage License application at the Office of the City Clerk, you must wait 24 hours before having your Marriage Ceremony, unless you obtain a judicial waiver. Learn how to obtain a judicial waiver.

**Comment by kaythaney** [comment]
👰 😍 👫

**Comment by riordan** [comment]
Apache2 or MIT

har har har

I'll show myself out...

**Comment by kaythaney** [comment]
MIT or BSD or BUST

On Fri, Apr 15, 2016 at 12:08 PM, David Riordan notifications@github.com
wrote:

> Apache2 or MIT
> 
> har har har
> 
> I'll show myself out...
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/thaneyriordan/plan/issues/11#issuecomment-210523442

## 

@kaythaney http://twitter.com/kaythaney/
@MozillaScience http://twitter.com/mozillascience

**Comment by kaythaney** [comment]
Need to create human + machine readable form.
