### ISSUE TITLE
Tent rental for inclament weather

### ISSUE THREAD

**Issue by riordan** [thaneyriordan/plan#18]
Working with Cabaret Tent and Party Rental to secure tent for The Farm on Adderly
# Details
- 1/3 upfront - nonrefundable
- Can cancel any time up to 48 hours before
- Frequently work with Stephen; will work with him to set up a load-in time
# Todos
- [x] Book with Cabaret Tent
- [x] Receive and pay upfront invoice
- [ ] Go/no-go decision
- [ ] Pay full fee

**Comment by riordan** [comment]
Pay first installment by tomorrow

**Comment by kaythaney** [comment]
Did you email over the credit card authorization? Please confirm.

**Comment by kaythaney** [comment]
nudge - please confirm ^^.
